import type { Exercise } from "./fitnessData";

const source = { label: "ACSM 저항·신체활동 일반 지침", url: "https://acsm.org/education-resources/trending-topics-resources/physical-activity-guidelines/" };
export const expandedExercisesPart10: Exercise[] = [
  { id: "single-leg-hip-hinge-support", name: "지지 싱글 레그 힙 힌지", englishName: "Supported Single-Leg Hip Hinge", category: "맨몸운동", regions: ["둔근", "하체", "코어"], focus: "균형", difficulty: "중급", equipment: "벽 또는 의자", minutes: "좌우 4–6회 · 2세트", description: "한 손으로 지지하며 엉덩이를 뒤로 보내는 편측 힌지·균형 변형입니다.", cues: ["지지대 가까이", "골반 정면", "작은 범위"], benefits: ["편측 힌지", "둔근 제어", "균형"], warning: "균형 상실·허리 통증·어지러움이 있으면 양발 힌지로 낮추세요.", reference: source },
  { id: "treadmill-incline-easy", name: "트레드밀 인클라인 이지", englishName: "Treadmill Incline Easy", category: "러닝", regions: ["하체", "둔근", "코어"], focus: "심폐", difficulty: "입문", equipment: "트레드밀", minutes: "2–5분 · 대화 가능한 강도", description: "낮은 경사와 편안한 보행 속도에서 경사 보행 리듬을 익히는 트레드밀 변형입니다.", cues: ["낮은 경사부터", "난간에 매달리지 않기", "대화 가능한 속도"], benefits: ["경사 적응", "심폐 활동", "둔근·하체 지구력"], warning: "벨트 속도·경사가 불편하거나 어지러움·통증이 있으면 즉시 정지하고 평지 보행으로 바꾸세요.", reference: source },
  { id: "machine-leg-press-easy", name: "머신 레그 프레스 이지", englishName: "Machine Leg Press Easy", category: "헬스기구", regions: ["하체", "둔근"], focus: "근력", difficulty: "입문", equipment: "레그 프레스 머신", minutes: "6–10회 · 2세트", description: "가벼운 중량과 짧은 범위에서 발 위치·등 지지·무릎 경로를 익히는 기구 하체 운동입니다.", cues: ["시트·핀 확인", "발 전체로 플랫폼 누르기", "무릎 잠그지 않기"], benefits: ["하체 근력", "기구 적응", "스쿼트 대체"], warning: "무릎·허리 통증, 안전장치 미확인, 너무 깊은 범위가 있으면 중단하고 중량·범위를 낮추세요.", reference: source },
  { id: "wall-sit-easy", name: "월 싯 이지", englishName: "Wall Sit Easy", category: "맨몸운동", regions: ["하체", "코어"], focus: "근력", difficulty: "입문", equipment: "단단한 벽", minutes: "10–20초 · 2–3회", description: "벽에 등을 대고 통증 없는 얕은 범위에서 짧게 유지하는 하체 지구력 변형입니다.", cues: ["발을 무릎보다 약간 앞에", "얕은 범위부터", "호흡 유지"], benefits: ["하체 지구력", "스쿼트 준비", "벽 지지 자세 인식"], warning: "무릎 통증·어지러움이 있으면 즉시 서서 쉬세요.", reference: source },
  { id: "knee-pushup-easy", name: "니 푸시업 이지", englishName: "Knee Push-up Easy", category: "맨몸운동", regions: ["가슴", "팔", "코어"], focus: "근력", difficulty: "입문", equipment: "매트", minutes: "4–8회 · 2세트", description: "무릎을 지지해 몸통을 길게 유지하며 수행하는 낮은 부하 푸시업 변형입니다.", cues: ["머리부터 무릎까지 길게", "팔꿈치 45도", "통증 없는 범위"], benefits: ["상체 밀기", "푸시업 진행 준비", "몸통 긴장 인식"], warning: "손목·어깨 통증이 있으면 높은 지지면 푸시업으로 바꾸세요.", reference: source },
  { id: "side-plank-knee", name: "사이드 플랭크 니", englishName: "Knee Side Plank", category: "맨몸운동", regions: ["코어", "둔근", "어깨"], focus: "협응", difficulty: "입문", equipment: "매트", minutes: "10–20초 · 좌우 2회", description: "무릎을 굽혀 지지하는 옆 플랭크로 옆몸통과 골반 제어를 익힙니다.", cues: ["팔꿈치를 어깨 아래", "골반을 짧게 들어올리기", "목 힘 빼기"], benefits: ["옆몸통 제어", "골반 안정성", "어깨 지지 준비"], warning: "어깨·허리 통증이 있으면 옆으로 누운 호흡으로 낮추세요.", reference: source },
  { id: "supported-split-squat", name: "지지 스플릿 스쿼트", englishName: "Supported Split Squat", category: "맨몸운동", regions: ["하체", "둔근", "코어"], focus: "근력", difficulty: "입문", equipment: "벽 또는 단단한 의자", minutes: "좌우 5–8회 · 2세트", description: "벽 또는 의자를 가볍게 잡고 짧은 범위에서 앞발로 바닥을 누르며 편측 하체 패턴을 익힙니다.", cues: ["지지대는 균형 보조만", "짧은 보폭·작은 범위", "앞발 전체로 지면 누르기"], benefits: ["편측 하체 근력", "균형", "런지 준비"], warning: "무릎·고관절 통증, 균형 상실, 체중 부하 불가가 있으면 벽 지지 체중 이동으로 낮추세요.", reference: source },
  { id: "dead-bug-heel-tap", name: "데드 버그 힐 탭", englishName: "Dead Bug Heel Tap", category: "맨몸운동", regions: ["코어", "하체"], focus: "협응", difficulty: "입문", equipment: "매트", minutes: "좌우 4–8회 · 2세트", description: "누운 자세에서 한쪽 발뒤꿈치를 바닥에 가볍게 터치하며 호흡과 몸통 제어를 연습합니다.", cues: ["갈비뼈·골반을 편안히", "허리 통증 없는 범위", "내쉬며 발 내리기"], benefits: ["몸통 제어", "호흡 협응", "허리 부담 조절"], warning: "허리 통증·저림이 커지면 다리 이동 범위를 줄이거나 중단하세요.", reference: source },
  { id: "prone-w-pull", name: "프론 W 풀", englishName: "Prone W Pull", category: "맨몸운동", regions: ["등", "어깨", "팔"], focus: "협응", difficulty: "입문", equipment: "매트 또는 벤치", minutes: "5–8회 · 2세트", description: "엎드린 자세에서 팔꿈치를 W 모양으로 당기며 목 힘을 빼고 등 상부의 가벼운 조절을 연습합니다.", cues: ["이마·목 편안히", "팔을 높이 들지 않기", "견갑을 가볍게 뒤로"], benefits: ["등 상부 조절", "당기기 기초", "어깨 자세 인식"], warning: "어깨 앞쪽 통증·목 통증·저림이 있으면 벽 로우 또는 밴드 로우로 전환하세요.", reference: source },
  { id: "bodyweight-good-morning", name: "맨몸 굿모닝", englishName: "Bodyweight Good Morning", category: "맨몸운동", regions: ["둔근", "하체", "코어"], focus: "협응", difficulty: "입문", equipment: "평평한 바닥", minutes: "6–10회 · 2세트", description: "손을 가슴 앞에 가볍게 두고 엉덩이를 뒤로 보내는 작은 힙 힌지를 연습합니다.", cues: ["허리보다 엉덩이를 뒤로", "발 전체로 바닥 누르기", "통증 없는 작은 범위"], benefits: ["힌지 패턴", "둔근·하체 협응", "들기 동작 준비"], warning: "허리 통증·어지러움·저림이 있으면 범위를 줄이거나 중단하세요.", reference: source },
  { id: "incline-plank-shoulder-tap", name: "인클라인 플랭크 숄더 탭", englishName: "Incline Plank Shoulder Tap", category: "맨몸운동", regions: ["코어", "어깨", "팔"], focus: "협응", difficulty: "입문", equipment: "단단한 카운터 또는 벽", minutes: "좌우 4–8회 · 2세트", description: "높은 지지면에서 몸통을 길게 유지하며 반대쪽 어깨를 가볍게 터치합니다.", cues: ["높은 지지면부터", "골반 흔들림 줄이기", "손목이 편안한 범위"], benefits: ["코어·어깨 협응", "상체 지지 준비", "교대 안정성"], warning: "손목·어깨 통증, 지지면 미끄러짐, 몸통 제어 상실이 있으면 벽 지지로 낮추세요.", reference: source },
  { id: "run-cadence-march", name: "러닝 케이던스 마치", englishName: "Running Cadence March", category: "러닝", regions: ["하체", "둔근", "코어"], focus: "협응", difficulty: "입문", equipment: "평평한 보행 경로", minutes: "20–30초 · 3–5회", description: "짧고 조용한 제자리 마치로 발 아래 리듬과 팔 스윙을 익히는 러닝 전 준비 드릴입니다.", cues: ["발은 몸 아래에", "작고 빠른 리듬", "어깨·턱 이완"], benefits: ["러닝 리듬 준비", "보행 협응", "워밍업"], warning: "발목·무릎 통증·어지러움이 있으면 편안한 걷기로 낮추세요.", reference: source },
  { id: "recovery-jog-walk", name: "리커버리 조그·워크", englishName: "Recovery Jog-Walk", category: "러닝", regions: ["하체", "둔근", "코어"], focus: "심폐", difficulty: "입문", equipment: "평평하고 안전한 경로", minutes: "30초 조깅 + 90초 걷기 · 4–6회", description: "말하기가 가능한 매우 느린 조깅과 충분한 걷기를 번갈아 수행하는 보수적 러닝 재도입입니다.", cues: ["조깅은 대화 가능한 속도", "걷기에서 호흡 회복", "통증 전 즉시 감속"], benefits: ["러닝 재도입", "심폐 적응", "페이스 조절"], warning: "날카로운 통증·흉통·어지러움·비정상적 숨참이 있으면 중단하고 평가를 우선하세요.", reference: source },
  { id: "machine-chest-press-easy", name: "머신 체스트 프레스 이지", englishName: "Machine Chest Press Easy", category: "헬스기구", regions: ["가슴", "어깨", "팔"], focus: "근력", difficulty: "입문", equipment: "체스트 프레스 머신", minutes: "6–10회 · 2–3세트", description: "시트와 손잡이를 몸에 맞추고 가벼운 저항에서 상체 밀기 경로를 연습합니다.", cues: ["시트 높이·등 지지 확인", "손목을 중립에", "반동 없이 천천히"], benefits: ["상체 밀기", "가슴·팔 근력", "기구 적응"], warning: "어깨 앞쪽 통증·손목 불편·시트 조절 불가가 있으면 중단하고 높은 지지면 푸시업으로 낮추세요.", reference: source },
  { id: "machine-seated-row-easy", name: "머신 시티드 로우 이지", englishName: "Machine Seated Row Easy", category: "헬스기구", regions: ["등", "팔", "어깨"], focus: "근력", difficulty: "입문", equipment: "시티드 로우 머신", minutes: "6–10회 · 2–3세트", description: "가슴 또는 발 지지를 조절한 머신에서 가벼운 저항으로 견갑·팔의 당기기 경로를 연습합니다.", cues: ["시트·지지대 먼저 조절", "목을 으쓱하지 않기", "천천히 복귀"], benefits: ["등·팔 근력", "견갑 조절", "당기기 기초"], warning: "어깨·팔 저림·허리 통증·기구 조절 불가가 있으면 중단하고 더 가벼운 지지 로우로 바꾸세요.", reference: source },
];
