import type { Exercise } from "./fitnessData";

const sources = {
  cdc: {
    label: "CDC 성인 신체 활동 지침",
    url: "https://www.cdc.gov/physical-activity-basics/guidelines/adults.html",
  },
  acsm: {
    label: "ACSM 신체 활동 지침",
    url: "https://acsm.org/education-resources/trending-topics-resources/physical-activity-guidelines/",
  },
  nsca: {
    label: "NSCA 플라이오메트릭 안내",
    url: "https://www.nsca.com/education/articles/kinetic-select/plyometric-exercises/",
  },
  nhs: {
    label: "NHS 통증 자가 관리",
    url: "https://www.nhs.uk/live-well/pain/10-ways-to-ease-pain/",
  },
};

export const expandedExercisesPart4: Exercise[] = [
  {
    id: "snap-down",
    name: "스냅 다운",
    englishName: "Snap Down",
    category: "파워·민첩성",
    regions: ["하체", "둔근", "코어"],
    focus: "파워",
    difficulty: "입문",
    equipment: "미끄럽지 않은 바닥",
    minutes: "2–3세트 · 3–5회",
    description:
      "발뒤꿈치를 가볍게 들었다가 조용히 반스쿼트 자세로 멈추며 착지 정렬을 익히는 저충격 파워 준비 운동입니다.",
    cues: [
      "무릎이 발끝 방향을 따라가게",
      "발 전체로 조용히 착지",
      "착지 뒤 1초 멈춰 정렬 확인",
    ],
    benefits: ["착지 제어", "하체 정렬 인식", "점프 준비"],
    warning:
      "무릎·발목·허리 통증, 균형 상실, 최근 하체 외상이 있으면 점프 계열 대신 걷기·근력 운동을 선택하세요.",
    reference: sources.nsca,
  },
  {
    id: "squat-jump-stick",
    name: "스쿼트 점프·스틱",
    englishName: "Squat Jump to Stick",
    category: "파워·민첩성",
    regions: ["하체", "둔근", "코어"],
    focus: "파워",
    difficulty: "중급",
    equipment: "미끄럽지 않은 바닥",
    minutes: "2–4세트 · 2–5회",
    description:
      "작은 범위로 뛰어오른 뒤 같은 자리에서 조용히 착지하고 멈추는 기본 수직 점프 연습입니다.",
    cues: [
      "낮은 점프 높이부터",
      "착지 때 무릎·고관절을 함께 부드럽게",
      "반복 사이 호흡과 정렬을 다시 확인",
    ],
    benefits: ["하체 파워", "착지 제어", "신장-단축 주기 연습"],
    warning:
      "착지 소리가 커지거나 정렬을 유지하지 못하면 즉시 반복을 끝내고 스냅 다운으로 낮추세요.",
    reference: sources.nsca,
  },
  {
    id: "pogo-hop",
    name: "포고 홉",
    englishName: "Pogo Hop",
    category: "파워·민첩성",
    regions: ["하체", "코어"],
    focus: "파워",
    difficulty: "중급",
    equipment: "평평한 바닥 · 지지대 근처",
    minutes: "10–20초 · 2–4회",
    description:
      "무릎을 깊게 굽히지 않고 발목을 중심으로 아주 작은 양발 점프를 반복하는 리듬·탄성 연습입니다.",
    cues: [
      "높이보다 가볍고 조용한 리듬",
      "몸통을 길게 유지",
      "피로 전에 짧게 끝내기",
    ],
    benefits: ["발목 탄성", "리듬 협응", "러닝·점프 준비"],
    warning:
      "종아리·아킬레스건·발 통증이 있거나 최근 달리기 부하가 많았다면 실시하지 마세요.",
    reference: sources.nsca,
  },
  {
    id: "lateral-bound-stick",
    name: "레터럴 바운드·스틱",
    englishName: "Lateral Bound to Stick",
    category: "파워·민첩성",
    regions: ["하체", "둔근", "코어"],
    focus: "파워",
    difficulty: "중급",
    equipment: "평평한 바닥 · 벽 근처",
    minutes: "좌우 2–3세트 · 3–5회",
    description:
      "옆으로 작은 거리를 이동한 뒤 한 발 또는 양발로 멈춰 측면 이동과 균형을 함께 연습합니다.",
    cues: [
      "거리를 매우 짧게 시작",
      "착지 뒤 1–2초 균형 유지",
      "골반이 한쪽으로 무너지지 않게",
    ],
    benefits: ["측면 이동 제어", "둔근·하체 파워", "균형 협응"],
    warning:
      "발목 삠 이력, 무릎 불안정, 균형 불안이 있으면 옆걸음·스텝 탭으로 바꾸세요.",
    reference: sources.nsca,
  },
  {
    id: "low-cone-shuffle",
    name: "로우 콘 셔플",
    englishName: "Low Cone Shuffle",
    category: "파워·민첩성",
    regions: ["하체", "둔근", "코어"],
    focus: "협응",
    difficulty: "입문",
    equipment: "낮은 콘 또는 표시물",
    minutes: "5–10m · 3–5회",
    description:
      "낮은 표시물 사이를 빠르기보다 통제된 옆걸음으로 이동하며 방향 전환 기초를 연습합니다.",
    cues: [
      "발을 교차하지 않고 옆으로 이동",
      "무릎을 부드럽게 굽히기",
      "방향 전환 전 속도를 줄이기",
    ],
    benefits: ["민첩성 기초", "측면 이동 협응", "하체 준비"],
    warning:
      "미끄러운 바닥·어지러움·무릎 통증이 있으면 진행하지 말고 평지 걷기를 선택하세요.",
    reference: sources.nsca,
  },
  {
    id: "medicine-ball-chest-pass",
    name: "메디신볼 체스트 패스",
    englishName: "Medicine Ball Chest Pass",
    category: "파워·민첩성",
    regions: ["가슴", "어깨", "팔", "코어"],
    focus: "파워",
    difficulty: "입문",
    equipment: "가벼운 메디신볼 · 안전한 벽",
    minutes: "2–3세트 · 3–6회",
    description:
      "가벼운 공을 가슴 앞에서 벽 또는 파트너에게 짧게 밀어 보내며 상체 힘 전달을 연습합니다.",
    cues: [
      "아주 가벼운 공으로 시작",
      "벽·파트너와 충분한 거리 확보",
      "팔꿈치를 잠그지 않고 부드럽게 받기",
    ],
    benefits: ["상체 파워", "몸통-팔 협응", "짧은 힘 전달"],
    warning:
      "어깨·손목 통증이 있거나 공을 안전하게 받을 공간이 없으면 실시하지 마세요.",
    reference: sources.nsca,
  },
  {
    id: "kettlebell-swing-prep",
    name: "케틀벨 스윙 프렙",
    englishName: "Kettlebell Swing Preparation",
    category: "프리웨이트",
    regions: ["둔근", "하체", "코어", "등"],
    focus: "협응",
    difficulty: "입문",
    equipment: "가벼운 케틀벨",
    minutes: "2–3세트 · 5–8회",
    description:
      "케틀벨을 바닥에서 짧게 들어 힙 힌지와 엉덩이 힘 전달을 연습하는 스윙 전 단계입니다.",
    cues: [
      "처음에는 힙 높이보다 낮게",
      "팔로 들어 올리지 않기",
      "등을 길게 유지하며 엉덩이로 일어서기",
    ],
    benefits: ["힙 힌지 숙련", "둔근·후면 사슬", "파워 패턴 준비"],
    warning:
      "허리 통증·어지러움·기술 불안이 있으면 스윙으로 진행하지 말고 케틀벨 데드리프트를 선택하세요.",
    reference: sources.acsm,
  },
  {
    id: "dumbbell-step-up",
    name: "덤벨 스텝업",
    englishName: "Dumbbell Step-Up",
    category: "프리웨이트",
    regions: ["하체", "둔근", "코어"],
    focus: "근력",
    difficulty: "중급",
    equipment: "낮은 스텝 · 가벼운 덤벨",
    minutes: "좌우 2–3세트 · 5–8회",
    description:
      "낮은 스텝을 한 발로 밟고 올라가며 한쪽 다리 힘과 보행 제어를 연습합니다.",
    cues: [
      "처음에는 덤벨 없이",
      "스텝 위 발 전체로 누르기",
      "내려올 때도 천천히 제어",
    ],
    benefits: ["한쪽 다리 근력", "둔근 활성", "계단 보행 준비"],
    warning:
      "스텝이 흔들리거나 무릎 통증·균형 불안이 있으면 지지대와 맨몸 변형으로 낮추세요.",
    reference: sources.acsm,
  },
  {
    id: "cable-chest-press",
    name: "케이블 체스트 프레스",
    englishName: "Cable Chest Press",
    category: "헬스기구",
    regions: ["가슴", "어깨", "팔", "코어"],
    focus: "근력",
    difficulty: "입문",
    equipment: "케이블 머신",
    minutes: "2–3세트 · 8–12회",
    description:
      "케이블 손잡이를 앞쪽으로 밀며 한쪽씩 또는 양쪽을 함께 사용하는 상체 밀기 운동입니다.",
    cues: [
      "가벼운 저항·안정된 자세",
      "갈비뼈를 과도하게 들지 않기",
      "손잡이를 천천히 되돌리기",
    ],
    benefits: ["가슴·팔 근력", "서기 자세 코어 제어", "상체 밀기 변형"],
    warning:
      "어깨 앞쪽 통증이나 몸통 회전 제어 상실이 있으면 중량·범위를 줄이거나 중단하세요.",
    reference: sources.acsm,
  },
  {
    id: "machine-hip-abduction",
    name: "머신 힙 어브덕션",
    englishName: "Machine Hip Abduction",
    category: "헬스기구",
    regions: ["둔근", "하체"],
    focus: "근력",
    difficulty: "입문",
    equipment: "힙 어브덕션 머신",
    minutes: "2–3세트 · 10–15회",
    description:
      "앉은 자세에서 패드를 바깥쪽으로 밀며 엉덩이 옆쪽의 부하를 조절하는 보조 머신 운동입니다.",
    cues: [
      "시트·등받이를 먼저 맞추기",
      "반동 없이 천천히 벌리기",
      "골반이 한쪽으로 기울지 않게",
    ],
    benefits: ["둔근 보조 근력", "골반 안정성", "한쪽 다리 운동 보조"],
    warning: "고관절 통증·저림이 생기면 범위와 중량을 줄이거나 중단하세요.",
    reference: sources.acsm,
  },
  {
    id: "machine-calf-raise",
    name: "머신 카프 레이즈",
    englishName: "Machine Calf Raise",
    category: "헬스기구",
    regions: ["하체"],
    focus: "근력",
    difficulty: "입문",
    equipment: "카프 레이즈 머신",
    minutes: "2–3세트 · 8–15회",
    description:
      "발 앞쪽 지지면에서 발목을 천천히 펴고 내리며 종아리의 부하와 발목 움직임을 연습합니다.",
    cues: [
      "가벼운 부하로 발목 범위 확인",
      "위·아래 모두 천천히",
      "무릎을 과도하게 잠그지 않기",
    ],
    benefits: ["종아리 근력", "발목 제어", "걷기·러닝 보조"],
    warning:
      "아킬레스건·발바닥·종아리의 날카로운 통증이 있으면 실시하지 마세요.",
    reference: sources.acsm,
  },
  {
    id: "chest-supported-row",
    name: "체스트 서포티드 로우",
    englishName: "Chest-Supported Row",
    category: "헬스기구",
    regions: ["등", "팔", "어깨"],
    focus: "근력",
    difficulty: "입문",
    equipment: "체스트 서포티드 로우 머신",
    minutes: "2–3세트 · 8–12회",
    description:
      "가슴을 패드에 지지하고 손잡이를 당겨 등 중심의 당기기 패턴을 연습하는 머신 운동입니다.",
    cues: [
      "가슴을 패드에 편안히 지지",
      "어깨를 귀에서 멀게",
      "팔꿈치를 몸통 가까이 당기기",
    ],
    benefits: ["등·팔 근력", "견갑 조절", "몸통 지지 당기기"],
    warning:
      "가슴 압박감·어깨 통증·저림이 있으면 자세와 패드를 조절하거나 중단하세요.",
    reference: sources.acsm,
  },
  {
    id: "stair-climber-easy",
    name: "스테어 클라이머 이지",
    englishName: "Easy Stair Climber",
    category: "유산소",
    regions: ["하체", "둔근", "코어"],
    focus: "심폐",
    difficulty: "입문",
    equipment: "스테어 클라이머",
    minutes: "10–25분 · RPE 4–6",
    description:
      "낮은 속도에서 계단 오르기 리듬을 유지하며 하체와 심폐 지구력을 기르는 실내 유산소 활동입니다.",
    cues: [
      "손잡이를 가볍게만 사용",
      "속도보다 일정한 리듬",
      "호흡이 과도하게 가빠지면 즉시 낮추기",
    ],
    benefits: ["심폐 지구력", "하체 반복 지구력", "계단 동작 적응"],
    warning:
      "무릎 통증·현기증·손잡이에 체중을 과도하게 싣는 자세가 나타나면 강도를 낮추거나 중단하세요.",
    reference: sources.cdc,
  },
  {
    id: "treadmill-walk-interval",
    name: "트레드밀 워크 인터벌",
    englishName: "Treadmill Walk Interval",
    category: "유산소",
    regions: ["하체", "둔근", "코어"],
    focus: "체력",
    difficulty: "입문",
    equipment: "트레드밀",
    minutes: "1–3분 걷기 구간 반복",
    description:
      "편안한 걷기와 약간 빠른 걷기를 번갈아 하며 고강도 달리기 없이 속도 변화를 경험하는 유산소 방식입니다.",
    cues: [
      "평지·낮은 경사에서 시작",
      "빠른 구간도 대화 가능한 범위",
      "손잡이를 잡고 속도를 바꾸지 않기",
    ],
    benefits: ["심폐 리듬", "걷기 속도 조절", "저충격 인터벌"],
    warning:
      "흉통·현기증·비정상적 숨참이 있으면 즉시 중단하고 평가를 받으세요.",
    reference: sources.cdc,
  },
  {
    id: "ankle-knee-to-wall",
    name: "발목 니투월 락",
    englishName: "Ankle Knee-to-Wall Rock",
    category: "모빌리티",
    regions: ["하체", "코어"],
    focus: "가동성",
    difficulty: "입문",
    equipment: "벽",
    minutes: "좌우 1–2세트 · 6–10회",
    description:
      "발뒤꿈치를 바닥에 둔 채 무릎을 벽 쪽으로 부드럽게 보내 발목 앞쪽 움직임을 탐색합니다.",
    cues: [
      "발뒤꿈치가 들리지 않게",
      "통증 없는 거리에서",
      "무릎은 두 번째 발가락 방향",
    ],
    benefits: ["발목 움직임 인식", "스쿼트·걷기 준비", "종아리 긴장 완화 보조"],
    warning:
      "발목 부종·최근 염좌·날카로운 통증이 있으면 강제로 늘리지 말고 평가를 받으세요.",
    reference: sources.nhs,
  },
  {
    id: "assisted-cossack-squat",
    name: "지지 Cossack 스쿼트",
    englishName: "Assisted Cossack Squat",
    category: "모빌리티",
    regions: ["하체", "둔근", "코어"],
    focus: "가동성",
    difficulty: "중급",
    equipment: "벽 또는 기둥 지지",
    minutes: "좌우 1–2세트 · 4–6회",
    description:
      "안정된 지지대를 잡고 한쪽으로 천천히 체중을 이동하며 고관절·발목의 편안한 범위를 탐색합니다.",
    cues: [
      "깊이보다 안정된 지지",
      "반대쪽 다리를 억지로 펴지 않기",
      "통증 없는 범위만 사용",
    ],
    benefits: ["측면 고관절 움직임", "한쪽 다리 준비", "가동 범위 인식"],
    warning:
      "무릎·고관절 통증이나 균형 불안이 있으면 더 쉬운 측면 체중 이동으로 낮추세요.",
    reference: sources.nhs,
  },
  {
    id: "clock-reach",
    name: "클락 리치",
    englishName: "Clock Reach",
    category: "균형·협응",
    regions: ["하체", "둔근", "코어"],
    focus: "협응",
    difficulty: "입문",
    equipment: "벽 또는 의자 근처",
    minutes: "좌우 1–2세트 · 3–5방향",
    description:
      "한 발로 안정적으로 서며 다른 발을 시계 방향의 여러 지점에 가볍게 뻗어 균형·도달 협응을 연습합니다.",
    cues: ["지지대 가까이 배치", "가까운 방향부터", "골반을 급히 돌리지 않기"],
    benefits: ["동적 균형", "엉덩이·발목 협응", "방향 감각"],
    warning:
      "최근 낙상·현기증·보행 불안이 있으면 혼자 난도를 올리지 말고 지지대를 사용하세요.",
    reference: sources.cdc,
  },
];
