import type { Exercise } from "./fitnessData";

const sources = {
  cdc: { label: "CDC 신체 활동 지침", url: "https://www.cdc.gov/physical-activity-basics/guidelines/adults.html" },
  older: { label: "CDC 고령자 활동·균형 지침", url: "https://www.cdc.gov/physical-activity-basics/guidelines/older-adults.html" },
  acsm: { label: "ACSM 신체 활동 지침", url: "https://acsm.org/education-resources/trending-topics-resources/physical-activity-guidelines/" },
  nhs: { label: "NHS 통증 자가 관리", url: "https://www.nhs.uk/live-well/pain/10-ways-to-ease-pain/" },
};

export const expandedExercisesPart2: Exercise[] = [
  { id: "brisk-walk", name: "빠른 걷기", englishName: "Brisk Walking", category: "러닝", regions: ["하체", "둔근", "코어"], focus: "심폐", difficulty: "입문", equipment: "편안한 신발", minutes: "20–45분 · 대화 가능한 강도", description: "팔을 자연스럽게 흔들며 평지 또는 완만한 길을 일정한 리듬으로 걷는 접근성 높은 유산소 활동입니다.", cues: ["시선은 정면에 두기", "보폭보다 리듬 우선", "어깨·손의 힘 빼기"], benefits: ["심폐 활동", "보행 지구력", "일상 활동량"], warning: "흉통, 현기증, 비정상적 숨참이 있으면 즉시 멈추고 평가를 받으세요.", reference: sources.cdc },
  { id: "hiking", name: "완만한 하이킹", englishName: "Easy Hiking", category: "러닝", regions: ["하체", "둔근", "코어"], focus: "체력", difficulty: "중급", equipment: "트레킹화 · 물", minutes: "30–90분 · 지형에 맞춰", description: "완만한 야외 지형을 걸으며 유산소 체력과 발목·하체 조절을 함께 사용하는 활동입니다.", cues: ["지형에 맞춰 속도 줄이기", "내리막에서 보폭 짧게", "물과 날씨 대비"], benefits: ["유산소 체력", "하체 지구력", "야외 보행 협응"], warning: "낯선 지형·더위·고도에서는 시간과 강도를 보수적으로 조절하세요.", reference: sources.cdc },
  { id: "air-bike", name: "에어 바이크 인터벌", englishName: "Air Bike Intervals", category: "유산소", regions: ["하체", "팔", "코어"], focus: "심폐", difficulty: "상급", equipment: "에어 바이크", minutes: "20초–1분 반복", description: "팔과 다리 페달을 함께 사용해 짧은 구간의 강도를 조절하는 전신 유산소 방식입니다.", cues: ["가벼운 워밍업으로 시작", "강한 구간 뒤 충분히 회복", "자세가 무너지면 즉시 강도 낮추기"], benefits: ["전신 심폐 자극", "인터벌 조절", "짧은 시간 체력"], warning: "심혈관 위험 요인·어지러움·흉통이 있으면 고강도 인터벌 전 의료진과 상의하세요.", reference: sources.cdc },
  { id: "assisted-pullup", name: "어시스트 풀업", englishName: "Assisted Pull-up", category: "헬스기구", regions: ["등", "팔", "어깨", "코어"], focus: "근력", difficulty: "중급", equipment: "어시스트 풀업 머신", minutes: "2–4세트 · 5–10회", description: "보조 중량을 활용해 수직 당기기 패턴을 점진적으로 익히는 머신 운동입니다.", cues: ["발·무릎 패드를 안정적으로 고정", "어깨를 귀에서 멀어지게", "반동 없이 천천히 복귀"], benefits: ["등·팔 근력", "수직 당기기", "체중 운동 준비"], warning: "어깨 통증이나 그립 통증이 있으면 보조량을 늘리고 범위를 낮추세요.", reference: sources.acsm },
  { id: "cable-triceps", name: "케이블 트라이셉스 프레스다운", englishName: "Cable Triceps Pressdown", category: "헬스기구", regions: ["팔"], focus: "근력", difficulty: "입문", equipment: "케이블 머신", minutes: "2–3세트 · 10–15회", description: "팔꿈치를 몸통 가까이에 두고 케이블을 아래로 밀며 팔 뒤쪽을 사용하는 보조 운동입니다.", cues: ["팔꿈치를 고정에 가깝게", "어깨를 앞으로 말지 않기", "복귀 구간을 천천히"], benefits: ["삼두근 근력", "상체 밀기 보조", "팔꿈치 제어"], warning: "팔꿈치 통증이 나타나면 그립·부하·반복 수를 낮추세요.", reference: sources.acsm },
  { id: "cable-biceps", name: "케이블 바이셉스 컬", englishName: "Cable Biceps Curl", category: "헬스기구", regions: ["팔"], focus: "근력", difficulty: "입문", equipment: "케이블 머신", minutes: "2–3세트 · 10–15회", description: "팔꿈치를 굽히며 팔 앞쪽을 사용하는 케이블 보조 운동입니다.", cues: ["팔꿈치를 옆구리 가까이", "몸통 반동 사용하지 않기", "손목을 과도하게 꺾지 않기"], benefits: ["팔 근력", "당기기 보조", "팔꿈치 굽힘 제어"], warning: "팔꿈치·손목 통증이 생기면 중량을 낮추고 그립을 조정하세요.", reference: sources.acsm },
  { id: "smith-squat", name: "스미스 머신 스쿼트", englishName: "Smith Machine Squat", category: "헬스기구", regions: ["하체", "둔근", "코어"], focus: "근력", difficulty: "중급", equipment: "스미스 머신", minutes: "3세트 · 6–12회", description: "가이드 바 경로 안에서 하체 스쿼트 패턴을 연습하는 머신 기반 저항 운동입니다.", cues: ["발 위치를 편안한 거리로 조절", "골반이 들리기 전 범위에서", "무게보다 안정된 제어 우선"], benefits: ["하체 근력", "스쿼트 패턴", "점진적 저항"], warning: "무릎·허리 통증이 있으면 깊이·발 위치·부하를 재조정하세요.", reference: sources.acsm },
  { id: "one-arm-row", name: "원암 덤벨 로우", englishName: "One-arm Dumbbell Row", category: "프리웨이트", regions: ["등", "팔", "코어"], focus: "근력", difficulty: "중급", equipment: "덤벨 · 벤치", minutes: "좌우 3세트 · 8–12회", description: "한 손으로 지지한 채 덤벨을 몸통 쪽으로 당겨 등과 팔의 당기기 패턴을 연습합니다.", cues: ["지지하는 손·무릎을 안정적으로", "팔꿈치를 골반 쪽으로 당기기", "몸통 회전 최소화"], benefits: ["등·팔 근력", "좌우 조절", "몸통 안정성"], warning: "허리 통증이 있으면 몸통을 더 지지하거나 가벼운 중량을 선택하세요.", reference: sources.acsm },
  { id: "bulgarian-split", name: "불가리안 스플릿 스쿼트", englishName: "Bulgarian Split Squat", category: "프리웨이트", regions: ["하체", "둔근", "코어"], focus: "근력", difficulty: "상급", equipment: "벤치 · 덤벨 선택", minutes: "좌우 2–3세트 · 6–10회", description: "뒤쪽 발을 낮은 벤치에 올리고 한쪽 다리로 하체 제어를 연습하는 운동입니다.", cues: ["처음에는 맨몸·낮은 지지면", "앞발 전체로 바닥 누르기", "균형이 흔들리면 지지대 활용"], benefits: ["한쪽 다리 근력", "둔근·대퇴 부하", "균형"], warning: "무릎 통증·균형 불안이 있다면 스플릿 스쿼트부터 충분히 연습하세요.", reference: sources.acsm },
  { id: "kettlebell-deadlift", name: "케틀벨 데드리프트", englishName: "Kettlebell Deadlift", category: "프리웨이트", regions: ["둔근", "하체", "등", "코어"], focus: "근력", difficulty: "입문", equipment: "케틀벨", minutes: "3세트 · 6–12회", description: "바닥의 케틀벨을 몸 가까이에서 들어 올리며 힙 힌지 기초를 배우는 운동입니다.", cues: ["엉덩이를 뒤로 보내기", "케틀벨을 몸 가까이", "등을 길게 유지"], benefits: ["후면 사슬 근력", "힙 힌지", "물건 들기 준비"], warning: "허리 통증·방사통이 있으면 수행하지 말고 전문가 평가를 받으세요.", reference: sources.acsm },
  { id: "calf-raise", name: "카프 레이즈", englishName: "Standing Calf Raise", category: "맨몸운동", regions: ["하체"], focus: "근력", difficulty: "입문", equipment: "벽 또는 의자 선택", minutes: "2–4세트 · 10–20회", description: "발 앞쪽으로 천천히 올라갔다 내려오며 종아리와 발목 조절을 연습하는 기초 운동입니다.", cues: ["벽 가까이에서 시작", "위·아래 움직임을 천천히", "발목이 바깥으로 무너지지 않게"], benefits: ["종아리 근력", "발목 조절", "보행·계단 준비"], warning: "아킬레스건 통증이 생기면 범위와 반복 수를 낮추거나 중단하세요.", reference: sources.cdc },
  { id: "side-plank", name: "사이드 플랭크 변형", englishName: "Side Plank Modification", category: "맨몸운동", regions: ["코어", "어깨", "둔근"], focus: "근력", difficulty: "중급", equipment: "매트", minutes: "좌우 15–30초 · 2–3회", description: "옆으로 누운 상태에서 팔꿈치 또는 손과 무릎·발로 몸을 지지하며 옆몸통 조절을 연습합니다.", cues: ["무릎 지지 변형부터 시작", "어깨를 귀에서 멀리", "골반을 과도하게 떨어뜨리지 않기"], benefits: ["옆몸통 지구력", "어깨 안정성", "골반 제어"], warning: "어깨·허리 통증이 생기면 지지점을 높이거나 중단하세요.", reference: sources.cdc },
  { id: "inverted-row", name: "인버티드 로우 변형", englishName: "Inverted Row Modification", category: "맨몸운동", regions: ["등", "팔", "코어"], focus: "근력", difficulty: "중급", equipment: "낮은 바 또는 안정된 TRX", minutes: "2–4세트 · 5–12회", description: "안정된 바 또는 스트랩을 잡고 몸통을 일직선으로 유지하며 가슴 쪽으로 당기는 운동입니다.", cues: ["장비 고정 상태 먼저 확인", "몸통을 길게 유지", "팔꿈치를 몸통 가까이 당기기"], benefits: ["등·팔 근력", "체중 당기기", "코어 긴장"], warning: "장비가 불안정하면 수행하지 말고, 어깨 통증이 있으면 각도를 높이세요.", reference: sources.acsm },
  { id: "wall-slide", name: "월 슬라이드", englishName: "Wall Slide", category: "모빌리티", regions: ["어깨", "등", "코어"], focus: "가동성", difficulty: "입문", equipment: "벽", minutes: "1–3세트 · 6–12회", description: "벽에 등을 가볍게 지지하고 팔을 위로 미끄러뜨리며 어깨·견갑 움직임을 탐색합니다.", cues: ["갈비뼈가 들리지 않게", "통증 없는 높이까지", "어깨를 으쓱하지 않기"], benefits: ["어깨 가동성", "견갑 조절", "상체 준비"], warning: "어깨 통증·저림이 증가하면 범위를 줄이고 평가를 받으세요.", reference: sources.nhs },
  { id: "hamstring-sweep", name: "햄스트링 스윕", englishName: "Hamstring Sweep", category: "모빌리티", regions: ["하체", "둔근"], focus: "가동성", difficulty: "입문", equipment: "없음", minutes: "좌우 6–10회", description: "한쪽 발뒤꿈치를 앞에 두고 엉덩이를 뒤로 보내며 다리 뒤쪽의 편안한 움직임을 탐색합니다.", cues: ["등을 과도하게 둥글게 말지 않기", "발끝을 당기되 힘 주지 않기", "작은 범위에서 리듬 있게"], benefits: ["햄스트링 가동성", "힙 힌지 준비", "걷기 전 준비"], warning: "다리 저림·방사통이 있으면 강한 스트레칭을 피하고 상담하세요.", reference: sources.nhs },
  { id: "lateral-weight-shift", name: "좌우 체중 이동", englishName: "Lateral Weight Shift", category: "균형·협응", regions: ["하체", "둔근", "코어"], focus: "균형", difficulty: "입문", equipment: "벽 또는 의자 근처", minutes: "좌우 8–12회", description: "안정된 지지대 가까이에서 체중을 한쪽 발로 부드럽게 옮기며 균형 조절을 연습합니다.", cues: ["발을 바닥에 넓게 유지", "천천히 체중 옮기기", "필요하면 한 손으로 지지"], benefits: ["좌우 균형", "고관절 조절", "보행 준비"], warning: "넘어질 위험이 있으면 반드시 지지대를 사용하고 혼자 어려운 변형을 시도하지 마세요.", reference: sources.older },
  { id: "toe-heel-walk", name: "발끝·뒤꿈치 걷기", englishName: "Toe-Heel Walk", category: "균형·협응", regions: ["하체", "코어"], focus: "협응", difficulty: "중급", equipment: "벽 옆의 평평한 바닥", minutes: "5–10걸음 · 2회", description: "짧은 거리에서 발끝과 뒤꿈치로 번갈아 걷는 발목·보행 협응 연습입니다.", cues: ["벽 가까이에서 시작", "발목을 급하게 꺾지 않기", "균형이 흔들리면 즉시 멈추기"], benefits: ["발목 협응", "동적 균형", "보행 감각"], warning: "어지러움·발목 통증·보행 불안이 있으면 실시하지 말고 더 쉬운 균형 연습을 선택하세요.", reference: sources.older },
  { id: "child-pose", name: "차일드 포즈", englishName: "Child's Pose", category: "요가·필라테스", regions: ["등", "어깨", "둔근"], focus: "가동성", difficulty: "입문", equipment: "매트", minutes: "20–60초 · 2회", description: "무릎을 접고 엉덩이를 뒤로 보내며 등과 어깨 주변을 편안하게 쉬게 하는 요가 자세입니다.", cues: ["무릎 사이 간격을 편안하게", "엉덩이가 발뒤꿈치에 닿지 않아도 괜찮기", "호흡을 길게 내쉬기"], benefits: ["등·어깨 이완", "호흡", "회복 루틴"], warning: "무릎·고관절 통증이 있으면 지지대를 사용하거나 다른 자세를 선택하세요.", reference: sources.nhs },
  { id: "pilates-bridge", name: "필라테스 브리지", englishName: "Pilates Bridge", category: "요가·필라테스", regions: ["둔근", "하체", "코어"], focus: "협응", difficulty: "입문", equipment: "매트", minutes: "2–3세트 · 6–12회", description: "누운 자세에서 척추를 편안하게 움직이며 엉덩이를 들어 올려 호흡·골반 조절을 연습합니다.", cues: ["척추를 하나씩 과하게 굴리지 않기", "엉덩이로 부드럽게 들어 올리기", "목에 힘 빼기"], benefits: ["둔근·코어 협응", "골반 조절", "호흡"], warning: "허리 통증이 생기면 높이를 줄이거나 글루트 브리지 변형을 선택하세요.", reference: sources.nhs },
];
