import type { Exercise } from "./fitnessData";

const sources = {
  cdc: { label: "CDC 성인 신체 활동 지침", url: "https://www.cdc.gov/physical-activity-basics/guidelines/adults.html" },
  acsm: { label: "ACSM 신체 활동 지침", url: "https://acsm.org/education-resources/trending-topics-resources/physical-activity-guidelines/" },
  older: { label: "CDC 고령자 활동·균형 지침", url: "https://www.cdc.gov/physical-activity-basics/guidelines/older-adults.html" },
  nhs: { label: "NHS 통증 자가 관리", url: "https://www.nhs.uk/live-well/pain/10-ways-to-ease-pain/" },
};

export const expandedExercisesPart3: Exercise[] = [
  { id: "incline-walk", name: "경사 트레드밀 걷기", englishName: "Incline Treadmill Walk", category: "유산소", regions: ["하체", "둔근", "코어"], focus: "심폐", difficulty: "입문", equipment: "트레드밀", minutes: "15–35분 · RPE 4–6", description: "속도보다 경사를 낮게부터 조절하며 걷기 리듬과 하체 지구력을 쌓는 저충격 유산소 활동입니다.", cues: ["손잡이에 체중을 과하게 싣지 않기", "보폭을 짧고 편안하게 유지", "경사는 한 단계씩만 조절"], benefits: ["심폐 활동", "둔근·하체 지구력", "실내 걷기 변형"], warning: "종아리·무릎·허리 통증이 커지거나 어지러우면 경사와 속도를 낮추거나 중단하세요.", reference: sources.cdc },
  { id: "sled-push", name: "라이트 슬레드 푸시", englishName: "Light Sled Push", category: "헬스기구", regions: ["하체", "둔근", "코어", "어깨"], focus: "체력", difficulty: "중급", equipment: "슬레드 · 평평한 바닥", minutes: "10–20m · 4–8회", description: "가벼운 썰매를 밀며 전신에 힘을 전달하는 짧은 거리의 컨디셔닝 운동입니다. 처음에는 기술과 보행 리듬을 우선합니다.", cues: ["손잡이를 안정적으로 잡기", "몸통을 길게 유지", "짧고 일정한 걸음으로 밀기"], benefits: ["전신 체력", "하체 추진", "짧은 거리 컨디셔닝"], warning: "미끄러운 바닥, 무릎·허리 통증, 현기증이 있으면 실시하지 말고 부하와 거리를 낮추세요.", reference: sources.acsm },
  { id: "machine-hamstring-curl", name: "머신 햄스트링 컬", englishName: "Machine Hamstring Curl", category: "헬스기구", regions: ["하체", "둔근"], focus: "근력", difficulty: "입문", equipment: "레그 컬 머신", minutes: "2–3세트 · 8–15회", description: "패드 위치를 맞춘 뒤 무릎을 굽혀 다리 뒤쪽을 쓰는 보조 저항 운동입니다.", cues: ["관절 축과 머신 축을 맞추기", "골반이 들리지 않게 지지", "반동 없이 천천히 복귀"], benefits: ["햄스트링 근력", "무릎 굽힘 조절", "하체 보조 운동"], warning: "무릎 뒤쪽 통증이나 경련이 생기면 가동 범위와 중량을 줄이세요.", reference: sources.acsm },
  { id: "cable-face-pull", name: "케이블 페이스 풀", englishName: "Cable Face Pull", category: "헬스기구", regions: ["등", "어깨", "팔"], focus: "근력", difficulty: "입문", equipment: "로프 케이블", minutes: "2–3세트 · 10–15회", description: "가벼운 로프 케이블을 얼굴 높이 쪽으로 당기며 상부 등과 어깨 뒤쪽의 제어를 연습하는 보조 운동입니다.", cues: ["가벼운 중량에서 시작", "팔꿈치를 편안한 대각선으로", "목에 힘을 주지 않기"], benefits: ["견갑 조절", "상부 등·어깨 뒤쪽", "당기기 보조"], warning: "어깨 앞쪽 충돌감이나 목 통증이 생기면 높이·그립·중량을 조절하거나 중단하세요.", reference: sources.acsm },
  { id: "pallof-press", name: "팔로프 프레스", englishName: "Pallof Press", category: "헬스기구", regions: ["코어", "어깨", "둔근"], focus: "협응", difficulty: "입문", equipment: "케이블 또는 밴드", minutes: "좌우 2–3세트 · 6–12회", description: "옆에서 당기는 저항에 맞서 팔을 앞으로 뻗으며 몸통이 회전하지 않도록 조절하는 코어 협응 운동입니다.", cues: ["가벼운 저항부터", "갈비뼈·골반을 편안하게 정렬", "팔을 뻗고 천천히 돌아오기"], benefits: ["몸통 회전 제어", "코어 협응", "서기 자세 안정"], warning: "허리 통증이 증가하면 저항을 줄이거나 지지면을 더 안정적으로 바꾸세요.", reference: sources.acsm },
  { id: "dumbbell-floor-press", name: "덤벨 플로어 프레스", englishName: "Dumbbell Floor Press", category: "프리웨이트", regions: ["가슴", "어깨", "팔"], focus: "근력", difficulty: "입문", equipment: "덤벨 · 매트", minutes: "2–4세트 · 6–12회", description: "바닥에 누워 덤벨을 밀며 팔꿈치가 바닥에 닿는 범위에서 상체 밀기 패턴을 연습합니다.", cues: ["덤벨을 안정적으로 잡기", "팔꿈치가 바닥에 닿으면 잠시 멈추기", "어깨를 으쓱하지 않기"], benefits: ["가슴·팔 근력", "상체 밀기", "바닥 지지 안정성"], warning: "덤벨을 안전하게 놓을 공간이 없거나 어깨 통증이 있으면 실시하지 마세요.", reference: sources.acsm },
  { id: "reverse-lunge", name: "리버스 런지", englishName: "Reverse Lunge", category: "맨몸운동", regions: ["하체", "둔근", "코어"], focus: "근력", difficulty: "중급", equipment: "벽 또는 의자 근처 선택", minutes: "좌우 2–3세트 · 6–10회", description: "한 발을 뒤로 보내 천천히 내려갔다 앞발로 바닥을 밀며 돌아오는 한쪽 다리 운동입니다.", cues: ["처음에는 지지대 가까이", "앞발 전체로 바닥 누르기", "보폭을 짧게 시작"], benefits: ["한쪽 다리 근력", "둔근·하체 조절", "보행 패턴"], warning: "무릎 통증·균형 불안이 있으면 범위를 낮추거나 의자 앉았다 일어나기로 바꾸세요.", reference: sources.cdc },
  { id: "suitcase-carry", name: "수트케이스 캐리", englishName: "Suitcase Carry", category: "프리웨이트", regions: ["코어", "팔", "하체"], focus: "협응", difficulty: "중급", equipment: "덤벨 또는 케틀벨", minutes: "좌우 15–30m · 2–4회", description: "한 손에 가벼운 무게를 들고 천천히 걸으며 몸통이 한쪽으로 기울지 않게 조절하는 캐리 운동입니다.", cues: ["가벼운 무게로 시작", "시선은 정면·보폭은 짧게", "어깨를 귀에서 멀리"], benefits: ["코어·그립 협응", "보행 안정성", "한쪽 부하 제어"], warning: "허리·어깨 통증이나 보행 불안이 있으면 무게를 낮추고 가까운 거리에서만 수행하세요.", reference: sources.acsm },
  { id: "wall-sit", name: "월 싯", englishName: "Wall Sit", category: "맨몸운동", regions: ["하체", "둔근", "코어"], focus: "근력", difficulty: "입문", equipment: "벽", minutes: "15–45초 · 2–4회", description: "벽에 등을 기대고 편안한 각도로 앉은 자세를 유지하며 하체 지구력을 기르는 정적 운동입니다.", cues: ["깊이를 낮게부터 시작", "발 전체를 바닥에 두기", "호흡을 멈추지 않기"], benefits: ["대퇴 지구력", "하체 정적 제어", "짧은 시간 근력"], warning: "무릎 앞쪽 통증이 생기면 각도를 높이거나 중단하세요.", reference: sources.cdc },
  { id: "quadruped-rockback", name: "네발 자세 락백", englishName: "Quadruped Rock Back", category: "모빌리티", regions: ["둔근", "하체", "등", "코어"], focus: "가동성", difficulty: "입문", equipment: "매트", minutes: "1–2세트 · 6–12회", description: "네발 자세에서 엉덩이를 뒤꿈치 쪽으로 부드럽게 보내며 고관절과 등 움직임을 탐색하는 준비 운동입니다.", cues: ["손으로 바닥을 가볍게 밀기", "허리가 불편하지 않은 범위", "호흡에 맞춰 천천히 왕복"], benefits: ["고관절 움직임 인식", "등·몸통 준비", "가벼운 회복"], warning: "무릎·고관절 통증이나 외상 뒤 불편이 있으면 범위를 줄이거나 평가를 받으세요.", reference: sources.nhs },
  { id: "ninety-ninety-hip-switch", name: "90·90 힙 스위치", englishName: "90-90 Hip Switch", category: "모빌리티", regions: ["둔근", "하체", "코어"], focus: "가동성", difficulty: "중급", equipment: "매트", minutes: "좌우 5–8회", description: "앉은 자세에서 양쪽 무릎의 방향을 바꾸며 고관절의 회전 움직임을 편안한 범위에서 연습합니다.", cues: ["손을 뒤에 짚고 시작", "통증 없는 범위만 사용", "속도보다 부드러운 전환"], benefits: ["고관절 회전 인식", "앉기·스쿼트 준비", "좌우 비교"], warning: "고관절·무릎에 날카로운 통증이 있으면 실시하지 말고 더 쉬운 가동성 운동을 선택하세요.", reference: sources.nhs },
  { id: "tandem-stance", name: "탠덤 스탠스", englishName: "Tandem Stance", category: "균형·협응", regions: ["하체", "코어"], focus: "균형", difficulty: "입문", equipment: "벽 또는 의자 근처", minutes: "20–30초 · 좌우 2회", description: "한 발의 뒤꿈치를 다른 발의 발끝 가까이에 두고 정지해 균형을 연습하는 기초 자세입니다.", cues: ["벽·의자 가까이에서 시작", "시선은 고정된 지점에", "필요하면 손가락으로 가볍게 지지"], benefits: ["정적 균형", "발목·고관절 조절", "보행 안정성"], warning: "최근 낙상, 현기증, 보행 불안이 있으면 혼자 난도를 올리지 말고 전문가와 상담하세요.", reference: sources.older },
];
