import type { Exercise } from "./fitnessData";

const sources = {
  acsm: { label: "ACSM 2026 저항운동 지침", url: "https://acsm.org/resistance-training-guidelines-update-2026/" },
  cdc: { label: "CDC 성인 신체 활동 지침", url: "https://www.cdc.gov/physical-activity-basics/guidelines/adults.html" },
  nscaRope: { label: "NSCA 배틀로프 컨디셔닝 안내", url: "https://www.nsca.com/education/articles/ptq/utilizing-battling-rope-exercises-for-hiit-and-smit/" },
};

export const expandedExercisesPart5: Exercise[] = [
  { id: "kettlebell-sumo-deadlift", name: "케틀벨 수모 데드리프트", englishName: "Kettlebell Sumo Deadlift", category: "프리웨이트", regions: ["둔근", "하체", "코어", "등"], focus: "근력", difficulty: "입문", equipment: "케틀벨", minutes: "2–3세트 · 6–10회", description: "조금 넓은 발 사이 바닥에 둔 케틀벨을 엉덩이와 무릎을 함께 굽혀 들어 올리며 하체 힘 전달을 연습합니다.", cues: ["케틀벨을 발 중앙 가까이에 두기", "무릎은 발끝 방향으로 편안하게", "팔보다 발과 엉덩이로 바닥 밀기"], benefits: ["힙 힌지 기초", "둔근·하체 근력", "넓은 스탠스 제어"], warning: "허리 통증·저림·기술 불안이 있으면 부하를 낮추거나 벽 힙 힌지로 돌아가세요.", reference: sources.acsm },
  { id: "kettlebell-goblet-squat", name: "케틀벨 고블릿 스쿼트", englishName: "Kettlebell Goblet Squat", category: "프리웨이트", regions: ["하체", "둔근", "코어"], focus: "근력", difficulty: "입문", equipment: "가벼운 케틀벨", minutes: "2–3세트 · 6–10회", description: "가벼운 케틀벨을 가슴 앞에 가까이 들고 편안한 범위로 앉았다 일어나며 하체 정렬을 연습합니다.", cues: ["케틀벨을 몸 가까이 안정적으로 잡기", "발 전체에 체중을 고르게 두기", "무릎과 발끝이 편안하게 같은 방향"], benefits: ["하체 근력", "몸통-하체 협응", "스쿼트 자세 인식"], warning: "무릎·허리 통증이 증가하면 의자 스쿼트나 맨몸 범위로 낮추세요.", reference: sources.acsm },
  { id: "kettlebell-suitcase-carry", name: "케틀벨 수트케이스 캐리", englishName: "Kettlebell Suitcase Carry", category: "프리웨이트", regions: ["코어", "팔", "하체"], focus: "협응", difficulty: "입문", equipment: "가벼운 케틀벨 · 평평한 바닥", minutes: "좌우 15–30m · 2–3회", description: "한 손에 가벼운 케틀벨을 들고 천천히 걸으며 몸통이 한쪽으로 기울지 않게 조절하는 운반 운동입니다.", cues: ["가벼운 무게로 짧은 거리부터", "어깨를 귀에서 멀리 두기", "짧고 조용한 보폭 유지"], benefits: ["그립·코어 협응", "보행 안정성", "한쪽 부하 제어"], warning: "어깨·허리 통증이나 보행 불안이 있으면 즉시 거리를 줄이거나 중단하세요.", reference: sources.acsm },
  { id: "resistance-band-row", name: "저항 밴드 로우", englishName: "Resistance Band Row", category: "프리웨이트", regions: ["등", "팔", "어깨"], focus: "근력", difficulty: "입문", equipment: "안정적으로 고정한 저항 밴드", minutes: "2–3세트 · 8–15회", description: "가슴 높이에 안전하게 고정한 밴드를 몸 쪽으로 당기며 등·견갑의 부드러운 당기기 패턴을 연습합니다.", cues: ["밴드 고정점을 먼저 두 번 확인", "어깨를 으쓱하지 않고 팔꿈치 당기기", "복귀 구간도 천천히 제어"], benefits: ["등·팔 근력", "견갑 조절", "가정 당기기 운동"], warning: "밴드가 손상됐거나 고정점이 불안정하면 사용하지 말고, 저림·어깨 통증이 있으면 중단하세요.", reference: sources.acsm },
  { id: "resistance-band-chest-press", name: "저항 밴드 체스트 프레스", englishName: "Resistance Band Chest Press", category: "프리웨이트", regions: ["가슴", "어깨", "팔", "코어"], focus: "근력", difficulty: "입문", equipment: "안정적으로 고정한 저항 밴드", minutes: "2–3세트 · 8–15회", description: "등 뒤의 안정된 고정점에서 밴드를 앞으로 밀며 상체 밀기와 몸통 제어를 연습합니다.", cues: ["밴드 고정점·손잡이 상태 확인", "갈비뼈를 과도하게 들지 않기", "팔꿈치를 잠그지 않고 부드럽게 복귀"], benefits: ["가슴·팔 근력", "서기 자세 제어", "가정 밀기 변형"], warning: "어깨 앞쪽 통증·밴드 끊김 위험·불안정한 고정점이 있으면 실시하지 마세요.", reference: sources.acsm },
  { id: "resistance-band-lateral-walk", name: "저항 밴드 사이드 워크", englishName: "Resistance Band Lateral Walk", category: "프리웨이트", regions: ["둔근", "하체", "코어"], focus: "협응", difficulty: "입문", equipment: "가벼운 루프 밴드", minutes: "5–8걸음 · 좌우 2–3회", description: "무릎 위 또는 발목 위에 가벼운 밴드를 두고 작은 옆걸음으로 둔근·골반 제어를 연습합니다.", cues: ["얕은 무릎 굽힘으로 시작", "발끝과 무릎 방향을 자연스럽게 맞추기", "보폭을 작게 유지"], benefits: ["둔근 활성 보조", "측면 보행 제어", "한쪽 다리 준비"], warning: "무릎·고관절 통증이나 균형 불안이 있으면 밴드를 빼고 짧은 옆걸음으로 낮추세요.", reference: sources.acsm },
  { id: "battle-rope-alternating-wave", name: "배틀로프 얼터네이팅 웨이브", englishName: "Battle Rope Alternating Wave", category: "파워·민첩성", regions: ["어깨", "팔", "코어", "하체"], focus: "체력", difficulty: "중급", equipment: "안전하게 고정한 배틀로프", minutes: "10–20초 · 2–5회", description: "낮은 반스쿼트 또는 안정된 서기 자세에서 로프를 좌우 번갈아 흔들며 전신 리듬과 짧은 컨디셔닝을 연습합니다.", cues: ["로프 고정점과 주변 공간 먼저 확인", "낮은 진폭·짧은 구간부터", "어깨를 귀에서 멀리 두고 리듬 유지"], benefits: ["상체 컨디셔닝", "전신 리듬", "짧은 심박 자극"], warning: "어지러움·흉통·어깨 통증·기술 붕괴가 나타나면 즉시 멈추고 충분히 회복하세요.", reference: sources.nscaRope },
  { id: "battle-rope-seated-wave", name: "시티드 배틀로프 웨이브", englishName: "Seated Battle Rope Wave", category: "파워·민첩성", regions: ["어깨", "팔", "코어"], focus: "체력", difficulty: "입문", equipment: "안정된 벤치 · 고정한 배틀로프", minutes: "10–15초 · 2–4회", description: "안정된 벤치에 앉아 로프를 작게 흔들며 다리 부담을 줄이고 상체 리듬을 경험하는 쉬운 변형입니다.", cues: ["벤치와 로프 고정점 확인", "허리를 과도하게 젖히지 않기", "짧은 구간 뒤 충분히 쉬기"], benefits: ["상체 리듬", "그립·어깨 지구력", "낮은 하체 부담"], warning: "어깨·목 통증이나 어지러움이 있으면 시도하지 말고 가벼운 밴드 운동으로 바꾸세요.", reference: sources.nscaRope },
  { id: "low-step-march", name: "로우 스텝 마치", englishName: "Low Step March", category: "균형·협응", regions: ["하체", "둔근", "코어"], focus: "협응", difficulty: "입문", equipment: "낮고 안정된 스텝", minutes: "좌우 5–10회 · 2세트", description: "낮은 스텝 위로 한 발씩 올라 무릎을 가볍게 들어 올린 뒤 천천히 내려오며 계단·균형 리듬을 연습합니다.", cues: ["스텝이 흔들리지 않는지 확인", "발 전체를 스텝 위에 올리기", "필요하면 벽·난간 가까이에서"], benefits: ["계단 리듬", "한쪽 다리 협응", "균형 준비"], warning: "체중 부하 불가·무릎 통증·최근 낙상이 있으면 스텝 대신 평지 마치로 낮추세요.", reference: sources.cdc },
  { id: "low-step-lateral-tap", name: "로우 스텝 레터럴 탭", englishName: "Low Step Lateral Tap", category: "균형·협응", regions: ["하체", "둔근", "코어"], focus: "협응", difficulty: "입문", equipment: "낮고 안정된 스텝 · 벽 근처", minutes: "좌우 5–8회 · 2세트", description: "스텝 옆에 서서 한 발을 위에 가볍게 터치하고 돌아오며 측면 체중 이동을 천천히 연습합니다.", cues: ["스텝 높이는 낮게 시작", "발을 교차하지 않고 옆으로 이동", "골반이 급하게 기울지 않게"], benefits: ["측면 이동 제어", "둔근·발목 협응", "방향 전환 준비"], warning: "발목·무릎 통증이나 균형 불안이 있으면 스텝 없이 바닥 탭으로 바꾸세요.", reference: sources.cdc },
  { id: "medicine-ball-scoop-toss", name: "메디신볼 스쿱 토스", englishName: "Medicine Ball Scoop Toss", category: "파워·민첩성", regions: ["하체", "둔근", "코어", "팔"], focus: "파워", difficulty: "입문", equipment: "아주 가벼운 메디신볼 · 안전한 벽", minutes: "2–3세트 · 3–5회", description: "가벼운 공을 낮은 자세에서 앞으로 부드럽게 보내며 하체·몸통·팔의 짧은 힘 전달을 연습합니다.", cues: ["아주 가벼운 공과 충분한 공간", "허리보다 엉덩이·다리로 힘 전달", "공을 안전하게 받거나 회수할 경로 확인"], benefits: ["전신 힘 전달", "몸통-팔 협응", "파워 패턴 기초"], warning: "허리·어깨·손목 통증이 있거나 공 반동을 제어할 수 없으면 실시하지 마세요.", reference: sources.acsm },
  { id: "aqua-walk", name: "수중 걷기", englishName: "Aqua Walking", category: "유산소", regions: ["하체", "둔근", "코어"], focus: "심폐", difficulty: "입문", equipment: "수심이 익숙한 수영장", minutes: "10–25분 · 편안한 리듬", description: "물속에서 천천히 걸으며 부력과 저항을 활용해 관절 충격을 낮춘 유산소 리듬을 경험합니다.", cues: ["수심과 바닥 상태를 먼저 확인", "난간 가까운 구간에서 시작", "보폭을 짧고 편안하게 유지"], benefits: ["저충격 유산소", "보행 리듬", "하체 순환감"], warning: "수영장 안전 규칙을 따르고, 어지러움·호흡 불편·물 공포가 있으면 혼자 진행하지 마세요.", reference: sources.cdc },
  { id: "elliptical-easy", name: "일립티컬 이지", englishName: "Easy Elliptical", category: "유산소", regions: ["하체", "둔근", "코어", "팔"], focus: "심폐", difficulty: "입문", equipment: "일립티컬 머신", minutes: "10–25분 · RPE 3–5", description: "낮은 저항에서 페달과 손잡이를 부드럽게 움직이며 달리기 충격을 줄인 전신 유산소 리듬을 연습합니다.", cues: ["페달 위 발 위치를 먼저 확인", "손잡이에 체중을 기대지 않기", "대화 가능한 강도로 시작"], benefits: ["저충격 심폐 활동", "전신 리듬", "걷기·달리기 대체"], warning: "현기증·무릎 통증·손잡이에 과도하게 의지하는 자세가 나오면 저항·시간을 낮추거나 중단하세요.", reference: sources.cdc },
  { id: "recumbent-bike-easy", name: "리컴번트 바이크 이지", englishName: "Easy Recumbent Bike", category: "유산소", regions: ["하체", "둔근"], focus: "심폐", difficulty: "입문", equipment: "리컴번트 바이크", minutes: "10–25분 · RPE 3–5", description: "등받이에 지지된 자세에서 낮은 저항으로 페달을 돌리며 하체 유산소 리듬을 쌓는 선택지입니다.", cues: ["시트 거리를 무릎이 너무 접히지 않게 조절", "낮은 저항으로 몇 분 적응", "발을 페달 중앙에 편안히 두기"], benefits: ["지지형 저충격 유산소", "하체 리듬", "운동 재개 선택지"], warning: "무릎·고관절 통증이 증가하거나 다리 저림이 생기면 시트·저항을 조절하거나 중단하세요.", reference: sources.cdc },
  { id: "row-erg-easy", name: "로잉 에르고미터 이지", englishName: "Easy Row Erg", category: "유산소", regions: ["등", "하체", "코어", "팔"], focus: "심폐", difficulty: "입문", equipment: "로잉 머신", minutes: "8–20분 · 낮은 저항", description: "낮은 저항에서 다리-몸통-팔 순서로 천천히 당기고 돌아오며 전신 유산소 리듬을 연습합니다.", cues: ["발 스트랩과 댐퍼를 낮게 설정", "다리로 밀고 몸통·팔을 뒤따르게", "허리를 젖히지 않고 부드럽게 복귀"], benefits: ["전신 유산소", "당기기 리듬", "다리·등 협응"], warning: "허리 통증·어지러움·손잡이를 당기며 등이 둥글어지는 자세가 생기면 강도와 범위를 낮추거나 중단하세요.", reference: sources.cdc },
];
