import type { Exercise } from "./fitnessData";

const source = { label: "ACSM 저항·신체활동 일반 지침", url: "https://acsm.org/education-resources/trending-topics-resources/physical-activity-guidelines/" };
export const expandedExercisesPart10: Exercise[] = [
  { id: "bodyweight-good-morning", name: "맨몸 굿모닝", englishName: "Bodyweight Good Morning", category: "맨몸운동", regions: ["둔근", "하체", "코어"], focus: "협응", difficulty: "입문", equipment: "평평한 바닥", minutes: "6–10회 · 2세트", description: "손을 가슴 앞에 가볍게 두고 엉덩이를 뒤로 보내는 작은 힙 힌지를 연습합니다.", cues: ["허리보다 엉덩이를 뒤로", "발 전체로 바닥 누르기", "통증 없는 작은 범위"], benefits: ["힌지 패턴", "둔근·하체 협응", "들기 동작 준비"], warning: "허리 통증·어지러움·저림이 있으면 범위를 줄이거나 중단하세요.", reference: source },
  { id: "incline-plank-shoulder-tap", name: "인클라인 플랭크 숄더 탭", englishName: "Incline Plank Shoulder Tap", category: "맨몸운동", regions: ["코어", "어깨", "팔"], focus: "협응", difficulty: "입문", equipment: "단단한 카운터 또는 벽", minutes: "좌우 4–8회 · 2세트", description: "높은 지지면에서 몸통을 길게 유지하며 반대쪽 어깨를 가볍게 터치합니다.", cues: ["높은 지지면부터", "골반 흔들림 줄이기", "손목이 편안한 범위"], benefits: ["코어·어깨 협응", "상체 지지 준비", "교대 안정성"], warning: "손목·어깨 통증, 지지면 미끄러짐, 몸통 제어 상실이 있으면 벽 지지로 낮추세요.", reference: source },
  { id: "run-cadence-march", name: "러닝 케이던스 마치", englishName: "Running Cadence March", category: "러닝", regions: ["하체", "둔근", "코어"], focus: "협응", difficulty: "입문", equipment: "평평한 보행 경로", minutes: "20–30초 · 3–5회", description: "짧고 조용한 제자리 마치로 발 아래 리듬과 팔 스윙을 익히는 러닝 전 준비 드릴입니다.", cues: ["발은 몸 아래에", "작고 빠른 리듬", "어깨·턱 이완"], benefits: ["러닝 리듬 준비", "보행 협응", "워밍업"], warning: "발목·무릎 통증·어지러움이 있으면 편안한 걷기로 낮추세요.", reference: source },
  { id: "recovery-jog-walk", name: "리커버리 조그·워크", englishName: "Recovery Jog-Walk", category: "러닝", regions: ["하체", "둔근", "코어"], focus: "심폐", difficulty: "입문", equipment: "평평하고 안전한 경로", minutes: "30초 조깅 + 90초 걷기 · 4–6회", description: "말하기가 가능한 매우 느린 조깅과 충분한 걷기를 번갈아 수행하는 보수적 러닝 재도입입니다.", cues: ["조깅은 대화 가능한 속도", "걷기에서 호흡 회복", "통증 전 즉시 감속"], benefits: ["러닝 재도입", "심폐 적응", "페이스 조절"], warning: "날카로운 통증·흉통·어지러움·비정상적 숨참이 있으면 중단하고 평가를 우선하세요.", reference: source },
  { id: "machine-chest-press-easy", name: "머신 체스트 프레스 이지", englishName: "Machine Chest Press Easy", category: "헬스기구", regions: ["가슴", "어깨", "팔"], focus: "근력", difficulty: "입문", equipment: "체스트 프레스 머신", minutes: "6–10회 · 2–3세트", description: "시트와 손잡이를 몸에 맞추고 가벼운 저항에서 상체 밀기 경로를 연습합니다.", cues: ["시트 높이·등 지지 확인", "손목을 중립에", "반동 없이 천천히"], benefits: ["상체 밀기", "가슴·팔 근력", "기구 적응"], warning: "어깨 앞쪽 통증·손목 불편·시트 조절 불가가 있으면 중단하고 높은 지지면 푸시업으로 낮추세요.", reference: source },
  { id: "machine-seated-row-easy", name: "머신 시티드 로우 이지", englishName: "Machine Seated Row Easy", category: "헬스기구", regions: ["등", "팔", "어깨"], focus: "근력", difficulty: "입문", equipment: "시티드 로우 머신", minutes: "6–10회 · 2–3세트", description: "가슴 또는 발 지지를 조절한 머신에서 가벼운 저항으로 견갑·팔의 당기기 경로를 연습합니다.", cues: ["시트·지지대 먼저 조절", "목을 으쓱하지 않기", "천천히 복귀"], benefits: ["등·팔 근력", "견갑 조절", "당기기 기초"], warning: "어깨·팔 저림·허리 통증·기구 조절 불가가 있으면 중단하고 더 가벼운 지지 로우로 바꾸세요.", reference: source },
];
