import type { Exercise } from "./fitnessData";

const sources = {
  acsm: { label: "ACSM 2026 저항운동 지침", url: "https://acsm.org/resistance-training-guidelines-update-2026/" },
  nscaCarry: { label: "NSCA 운반 운동 안내", url: "https://www.nsca.com/education/articles/nsca-coach/increase-hip-and-trunk-stability-with-loaded-carries/" },
  aceSuspension: { label: "ACE 서스펜션 트레이닝 안내", url: "https://www.acefitness.org/continuing-education/certified/september-2022/8128/get-suspended-a-workout-to-maximize-the-proven-health-benefits-of-suspension-training/" },
  redCrossSwim: { label: "American Red Cross 수영 안전 안내", url: "https://www.redcross.org/get-help/how-to-prepare-for-emergencies/types-of-emergencies/water-safety/swim-safety.html" },
};

export const expandedExercisesPart6: Exercise[] = [
  { id: "sandbag-bear-hug-carry", name: "샌드백 베어허그 캐리", englishName: "Sandbag Bear-Hug Carry", category: "프리웨이트", regions: ["하체", "둔근", "코어", "팔", "등"], focus: "체력", difficulty: "중급", equipment: "가벼운 샌드백 · 평평한 보행 경로", minutes: "10–25m · 2–4회", description: "가벼운 샌드백을 몸 앞 가까이 안고 짧은 거리를 통제해 걸으며 전신 운반과 보행 리듬을 연습합니다.", cues: ["가벼운 샌드백·짧은 경로부터", "몸통을 길게 세우고 짧게 걷기", "방향 전환 전 속도를 줄이기"], benefits: ["전신 운반 지구력", "몸통·그립 협응", "보행 제어"], warning: "허리·어깨 통증, 숨참, 몸통이 크게 기울어짐이 있으면 거리·부하를 낮추거나 중단하세요.", reference: sources.nscaCarry },
  { id: "sandbag-front-squat", name: "샌드백 프런트 스쿼트", englishName: "Sandbag Front Squat", category: "프리웨이트", regions: ["하체", "둔근", "코어", "팔"], focus: "근력", difficulty: "중급", equipment: "가벼운 샌드백", minutes: "2–3세트 · 5–8회", description: "가벼운 샌드백을 몸 앞쪽에 안정적으로 두고 편안한 범위의 스쿼트를 수행하는 기능성 하체 운동입니다.", cues: ["샌드백을 몸에 가깝게 밀착", "발 전체로 바닥 누르기", "깊이보다 정렬과 호흡 우선"], benefits: ["하체·둔근 근력", "앞쪽 부하 제어", "몸통 협응"], warning: "무릎·허리 통증이나 샌드백을 제어할 수 없는 흔들림이 있으면 맨몸·고블릿 스쿼트로 낮추세요.", reference: sources.acsm },
  { id: "trx-row", name: "TRX 로우", englishName: "TRX Row", category: "맨몸운동", regions: ["등", "팔", "어깨", "코어"], focus: "근력", difficulty: "입문", equipment: "안전하게 고정한 서스펜션 스트랩", minutes: "2–3세트 · 6–12회", description: "발 위치로 각도를 조절하며 스트랩 손잡이를 몸 쪽으로 당겨 등·견갑의 제어를 연습합니다.", cues: ["고정점·스트랩 마모 먼저 확인", "몸을 긴 선으로 유지", "어깨를 으쓱하지 않고 손잡이 당기기"], benefits: ["등·팔 근력", "견갑 제어", "가변 난도 당기기"], warning: "고정점이 불안정하거나 어깨 통증·저림이 있으면 사용하지 말고 밴드 로우로 바꾸세요.", reference: sources.aceSuspension },
  { id: "trx-assisted-squat", name: "TRX 어시스티드 스쿼트", englishName: "TRX Assisted Squat", category: "맨몸운동", regions: ["하체", "둔근", "코어"], focus: "근력", difficulty: "입문", equipment: "안전하게 고정한 서스펜션 스트랩", minutes: "2–3세트 · 6–12회", description: "스트랩을 가볍게 잡아 균형을 보조하며 스쿼트의 편안한 범위와 하체 제어를 연습합니다.", cues: ["팔로 몸을 당기지 않고 가볍게 지지", "발 전체와 무릎 방향 확인", "통증 없는 깊이에서 멈추기"], benefits: ["스쿼트 자신감", "균형 보조", "하체 근력 기초"], warning: "무릎 통증·현기증·고정점 불안이 있으면 의자 스쿼트와 벽 지지로 낮추세요.", reference: sources.aceSuspension },
  { id: "trx-chest-press", name: "TRX 체스트 프레스", englishName: "TRX Chest Press", category: "맨몸운동", regions: ["가슴", "어깨", "팔", "코어"], focus: "근력", difficulty: "중급", equipment: "안전하게 고정한 서스펜션 스트랩", minutes: "2–3세트 · 5–10회", description: "스트랩을 잡고 몸을 한 선으로 기울여 팔을 굽혔다 펴며 상체 밀기와 몸통 제어를 연습합니다.", cues: ["각도를 낮게 시작해 부하 조절", "갈비뼈를 과도하게 들지 않기", "팔꿈치를 편안한 대각선으로"], benefits: ["가슴·팔 근력", "상체 밀기 제어", "몸통 안정성"], warning: "어깨 앞쪽 통증·손목 불편·고정점 불안이 있으면 더 높은 각도 또는 벽 푸시업으로 낮추세요.", reference: sources.aceSuspension },
  { id: "club-bell-front-hold-march", name: "클럽벨 프런트 홀드 마치", englishName: "Clubbell Front Hold March", category: "프리웨이트", regions: ["코어", "어깨", "팔", "하체"], focus: "협응", difficulty: "입문", equipment: "아주 가벼운 클럽벨", minutes: "20–30초 · 2–3회", description: "아주 가벼운 클럽벨을 세로로 몸 앞에 두고 제자리에서 천천히 마치하며 몸통·어깨의 안정성을 연습합니다.", cues: ["아주 가벼운 도구부터", "클럽벨이 몸에서 멀어지지 않게", "작고 조용한 제자리 걸음"], benefits: ["그립·몸통 협응", "어깨 위치 인식", "운반 패턴 준비"], warning: "손목·어깨 통증, 도구 제어 상실, 어지러움이 있으면 즉시 중단하고 맨몸 마치로 낮추세요.", reference: sources.acsm },
  { id: "club-bell-two-hand-swing-prep", name: "클럽벨 투핸드 스윙 프렙", englishName: "Clubbell Two-Hand Swing Preparation", category: "프리웨이트", regions: ["둔근", "하체", "코어", "어깨"], focus: "협응", difficulty: "입문", equipment: "아주 가벼운 클럽벨 · 넓은 공간", minutes: "2–3세트 · 4–6회", description: "두 손으로 아주 가벼운 클럽벨을 짧은 범위에서 앞뒤로 이동하며 힙 힌지와 도구 경로를 익히는 준비 운동입니다.", cues: ["도구가 지나갈 공간 충분히 확보", "허리보다 엉덩이로 접고 일어서기", "어깨 높이 이하의 짧은 범위 유지"], benefits: ["힙 힌지 협응", "도구 경로 인식", "그립 준비"], warning: "어깨·허리 통증, 좁은 공간, 도구 흔들림을 제어하지 못하는 경우에는 실시하지 마세요.", reference: sources.acsm },
  { id: "supported-dead-hang", name: "지지 데드 행", englishName: "Supported Dead Hang", category: "맨몸운동", regions: ["등", "어깨", "팔", "코어"], focus: "가동성", difficulty: "입문", equipment: "안정된 바 · 발 지지대", minutes: "5–15초 · 2–4회", description: "발을 바닥 또는 지지대에 일부 둔 채 안정된 바를 가볍게 잡아 어깨 위쪽의 편안한 매달리기 감각을 탐색합니다.", cues: ["바 고정 상태와 발 지지 확인", "발로 체중 일부를 계속 지지", "목을 으쓱하지 않고 짧게 유지"], benefits: ["어깨 위치 인식", "그립 준비", "상체 가동성 탐색"], warning: "어깨 불안정·저림·통증·손 미끄러짐이 있으면 매달리지 말고 벽 슬라이드로 바꾸세요.", reference: sources.acsm },
  { id: "scapular-hang", name: "스캐풀라 행", englishName: "Scapular Hang", category: "맨몸운동", regions: ["등", "어깨", "팔"], focus: "협응", difficulty: "중급", equipment: "안정된 바 · 발 지지대 선택", minutes: "3–6회 · 2세트", description: "안정된 바를 잡고 팔꿈치를 펴 둔 채 어깨를 아주 작게 올렸다 내리며 견갑 조절을 연습합니다.", cues: ["작은 범위만 사용", "팔꿈치를 구부려 당기지 않기", "목을 길게 유지"], benefits: ["견갑 조절", "매달리기 준비", "등·어깨 협응"], warning: "어깨 통증·저림·매달리기 불안이 있으면 수행하지 말고 밴드 로우·월 슬라이드로 낮추세요.", reference: sources.acsm },
  { id: "landmine-press", name: "랜드마인 프레스", englishName: "Landmine Press", category: "프리웨이트", regions: ["어깨", "가슴", "팔", "코어"], focus: "근력", difficulty: "중급", equipment: "안전하게 고정한 랜드마인 바", minutes: "좌우 2–3세트 · 6–10회", description: "바의 한쪽 끝을 대각선 앞으로 밀며 완전한 머리 위 밀기보다 낮은 각도에서 어깨·몸통 제어를 연습합니다.", cues: ["바 고정·주변 공간을 먼저 확인", "갈비뼈와 골반을 편안히 정렬", "통증 없는 대각선 경로로 밀기"], benefits: ["대각선 밀기", "어깨·코어 협응", "상체 근력"], warning: "어깨 통증·허리 과신전·바 고정 불안이 있으면 실시하지 말고 가벼운 체스트 프레스로 낮추세요.", reference: sources.acsm },
  { id: "landmine-row", name: "랜드마인 로우", englishName: "Landmine Row", category: "프리웨이트", regions: ["등", "팔", "코어", "하체"], focus: "근력", difficulty: "중급", equipment: "안전하게 고정한 랜드마인 바", minutes: "2–3세트 · 6–10회", description: "힌지 자세에서 랜드마인 바 끝을 몸 쪽으로 당기며 등 중심의 당기기와 몸통 정렬을 연습합니다.", cues: ["가벼운 부하·짧은 힌지부터", "팔꿈치를 몸통 가까이 당기기", "허리가 둥글어지면 범위 줄이기"], benefits: ["등·팔 근력", "힌지 속 당기기", "몸통 제어"], warning: "허리·어깨 통증, 바 고정 불안, 피로로 정렬이 무너지면 즉시 중단하세요.", reference: sources.acsm },
  { id: "landmine-rotation-prep", name: "랜드마인 회전 프렙", englishName: "Landmine Rotation Preparation", category: "프리웨이트", regions: ["코어", "둔근", "하체", "어깨"], focus: "협응", difficulty: "입문", equipment: "안전하게 고정한 랜드마인 바 · 가벼운 부하", minutes: "좌우 2세트 · 4–6회", description: "가벼운 랜드마인 바를 두 손으로 잡고 몸통·골반이 함께 움직이는 작은 대각선 회전 경로를 안전하게 연습하는 준비 운동입니다.", cues: ["바 고정과 넓은 반경 먼저 확인", "아주 작은 범위에서 골반과 몸통 함께 이동", "허리를 비틀지 말고 발로 방향 전환"], benefits: ["회전 패턴 인식", "몸통·둔근 협응", "대각선 부하 준비"], warning: "허리·고관절·어깨 통증, 바 고정 불안, 제어되지 않는 속도가 있으면 중단하고 팔로프 프레스로 바꾸세요.", reference: sources.acsm },
  { id: "seated-wrist-mobility", name: "시티드 손목 가동성", englishName: "Seated Wrist Mobility", category: "모빌리티", regions: ["팔"], focus: "가동성", difficulty: "입문", equipment: "안정된 의자 · 테이블 선택", minutes: "좌우 6–10회 · 1–2세트", description: "앉은 자세에서 팔꿈치를 편안히 지지하고 손목을 작은 범위로 굽혔다 펴며 전완·손목의 부담을 낮추는 가동성 탐색입니다.", cues: ["통증 없는 작은 범위부터", "팔꿈치와 어깨를 편안히 지지", "반동 없이 천천히 왕복"], benefits: ["손목 위치 인식", "전완 긴장 완화", "그립 운동 전 준비"], warning: "외상 뒤 변형·급성 붓기·감각 저하·뚜렷한 힘 빠짐이 있으면 자가 운동보다 의료 평가를 우선하세요.", reference: sources.acsm },
  { id: "pool-easy-swim", name: "이지 수영", englishName: "Easy Pool Swim", category: "유산소", regions: ["등", "어깨", "코어", "하체"], focus: "심폐", difficulty: "입문", equipment: "안전 관리가 되는 수영장 · 수경 선택", minutes: "10–20분 · 쉬는 구간 포함", description: "감시 인력·동반자·수심이 확인된 수영장에서 짧은 길이를 편안한 호흡으로 반복하는 저강도 수중 유산소 운동입니다.", cues: ["혼자 수영하지 않고 안전 구역에서 시작", "한 길이 뒤 충분히 호흡·휴식", "숨참·어지러움이 오기 전 물 밖에서 쉬기"], benefits: ["저충격 심폐 활동", "전신 협응", "호흡 리듬 탐색"], warning: "수영 능력·수심·감시 인력이 불확실하거나 숨참·흉통·어지러움이 있으면 물에 들어가지 말고 즉시 도움을 요청하세요.", reference: sources.redCrossSwim },
];
