import { Sparkles } from "lucide-react";
import { useEffect, useState } from "react";
import type { WeeklyPlan } from "@/lib/weeklyPlan";
import { readLocalWellnessPreferences, type RecoveryReflection } from "@/lib/wellnessPreferences";

type WeeklyFlowDay = { weekday: string; planned: number; completed: number };

export function WeeklyAtlasDetailReport({ flow, goal, onGoal, direction, onOpenSession }: { flow: WeeklyFlowDay[]; goal: WeeklyPlan["goal"]; onGoal: (goal: WeeklyPlan["goal"]) => void; direction: string; onOpenSession: () => void }) {
  const [recoveryHistory, setRecoveryHistory] = useState(() => readLocalWellnessPreferences().recoveryHistory);
  useEffect(() => { const refresh = () => setRecoveryHistory(readLocalWellnessPreferences().recoveryHistory); window.addEventListener("fit-atlas-recovery", refresh); return () => window.removeEventListener("fit-atlas-recovery", refresh); }, []);
  const recentHistory = recoveryHistory.slice(0, 4);
  const recentReflections = recentHistory.map((record) => record.reflection).filter((reflection): reflection is RecoveryReflection => Boolean(reflection));
  const recoverySignal = recentReflections.length === 0 ? "회복 기록을 남기면 최근 4회 신호가 연결됩니다." : recentReflections[0] === "pause" ? "최근 쉬어가기 신호 · 다음 세션은 가볍게 시작" : recentReflections.slice(0, 2).every((reflection) => reflection === "lighter") ? "최근 가벼워짐 흐름 · 현재 리듬 유지" : "최근 체감 혼합 · 다음 세션은 범위를 보수적으로";
  return <section className="weekly-atlas-detail-report" aria-label="주간 아틀라스 상세 리포트"><div className="weekly-detail-head"><div><p className="eyebrow">WEEKLY FLOW</p><h2>주간 완료 흐름</h2></div><p>완료 / 계획</p></div><div className="weekly-flow-chart" role="img" aria-label={flow.map((day) => `${day.weekday}요일 계획 ${day.planned}개 중 완료 ${day.completed}개`).join(", ")}>{flow.map((day) => <article key={day.weekday} className={day.completed ? "is-complete" : day.planned ? "is-planned" : ""}><span>{day.weekday}</span><div><i style={{ height: `${day.planned ? 38 + Math.min(day.planned, 3) * 16 : 4}%` }} /><b style={{ height: `${day.planned ? Math.max((day.completed / day.planned) * 100, day.completed ? 16 : 4) : 4}%` }} /></div><small>{day.completed}/{day.planned}</small></article>)}</div><div className="weekly-detail-bottom"><div className="weekly-goal-editor" role="group" aria-label="이번 주 운동 목표"><span>이번 주 목표</span>{(["all_round", "strength", "endurance"] as WeeklyPlan["goal"][]).map((item) => <button key={item} className={goal === item ? "is-selected" : ""} aria-pressed={goal === item} onClick={() => onGoal(item)}>{{ all_round: "전신", strength: "근력", endurance: "심폐" }[item]}</button>)}</div><div className="weekly-next-action"><p className="weekly-direction"><Sparkles size={16} /><span>{direction}</span></p><p className="weekly-recovery-signal" aria-label="주간 회복 추세 신호">{recoverySignal}</p>{recentHistory.length > 0 && <ol className="weekly-recovery-mini" aria-label="주간 회복 날짜별 추세">{[...recentHistory].reverse().map((record, index) => <li key={`${record.completedAt ?? record.completedOn}-${index}`} className={record.reflection ? `is-${record.reflection}` : "is-pending"}><span>{record.completedOn.slice(5)}</span><b>{record.reflection === "lighter" ? "↑" : record.reflection === "pause" ? "!" : record.reflection === "same" ? "·" : "?"}</b></li>)}</ol>}<p className="weekly-next-route" aria-label="주간 리포트 다음 세션 경로"><span>01 주간 신호 확인</span><span>02 {{ all_round: "전신", strength: "근력", endurance: "심폐" }[goal]} 세션 조절</span></p><button type="button" onClick={onOpenSession}>다음 세션 설계</button></div></div></section>;
}
